# Конфигурационный файл

dev:

    # Наименование окружения
    name: citycard development environment

    # подключение к БД
    mysql:
        username: root
        password: password
        isDebug: true
        dsn: mysql:host=localhost;dbname=dev-db

production:

    # Наименование окружения
    name: PRODUCTION environment

    # подключение к БД
    mysql:
        username: user
        password: password
        isDebug: false
        dsn: mysql:host=localhost;dbname=production-db