# Конфигурационный файл

dev:

    name: citycard development environment

    # подключение к БД
    mongo:
        username: root
        password: password
        isDebug: true
        dsn: mysql:host=ubuntu;dbname=box


    # секция для загрузки сборок на серверы
    servers:
        19323:
            active: true
            host: myhost
            password: dsdsds

        193231:
            active: false
            host: myhost
            password: dsdsds

        193232:
            active: false
            host: myhost
            password: dsdsds

production:

    # Описание Meme-проекта
    name: citycard PRODUCTION environment

    # подключение к БД
    mongo:
        server: mongodb://cityUser:password@localhost/citycard
        dbname: citycard