# Конфигурационный файл для 'dev' окружения
name: citycard development

# секция для загрузки сборок на серверы
servers:
    19323:
        active: true
        host: myhost
        password: dsdsds

    193231:
        active: false
        host: myhost
        password: dsdsds

    193232:
        active: false
        host: myhost
        password: dsdsds
